### ISSUE TITLE
Backup work but not restore

### ISSUE THREAD

**Issue by nemsia** [YunoHost-Apps/mastodon_ynh#10]
restore mastodon backup fail with:
```
2017-04-20 20:09:07,583 INFO yunohost.hook <lambda> - [3300.1] + sudo su -c psql postgres
2017-04-20 20:09:07,885 WARNING yunohost.hook <lambda> - [3300.1] could not change directory to "/home/yunohost.backup/tmp/20170420-165809/apps/mastodon/backup": Permission denied
2017-04-20 20:09:08,000 INFO yunohost.hook <lambda> - [3300.1] CREATE ROLE
2017-04-20 20:09:08,019 INFO yunohost.hook <lambda> - [3300.1] + sudo su - postgres
2017-04-20 20:09:08,318 WARNING yunohost.hook <lambda> - [3300.1] -su: line 1: /home/yunohost.backup/tmp/20170420-165809/apps/mastodon/backup/mastodon_db.sql: Permission denied
2017-04-20 20:09:08,564 ERROR yunohost.backup backup_restore - [3300.1] Unable to restore the app 'mastodon'
Traceback (most recent call last):
File "/usr/lib/moulinette/yunohost/backup.py", line 527, in backup_restore
raise_on_error=True, chdir=tmp_app_bkp_dir, env=env_dict)
File "/usr/lib/moulinette/yunohost/hook.py", line 367, in hook_exec
errno.EIO, m18n.n('hook_exec_failed', path=path))
MoulinetteError: [Errno 5] Script execution failed: /tmp/restore_mastodon
2017-04-20 20:09:08,830 INFO yunohost.hook hook_exec - [3300.1] Executing script '/tmp/remove_mastodon'...
```
I work on it:
https://github.com/nemsia/mastodon_ynh/commit/6e6f3cd38d0f589415ab71acd5c00d487f0b668e

**Comment by magikcypress** [comment]
This bug fix is not ok for you ?

**Comment by nemsia** [comment]
Restore don't work nées more tome to fix ;)

**Comment by nemsia** [comment]
Solved by https://github.com/YunoHost-Apps/mastodon_ynh/commit/35275b3a7824d70e9bfdef0fe7803d14dfd053d9
