### ISSUE TITLE
Installation fails : missing path in mastodon-streaming.service ?

### ISSUE THREAD

**Issue by anubister** [YunoHost-Apps/mastodon_ynh#126]
Hello,
i'm unable to install the develop version (95745611d4dd81ba87e2da36f4ce59875f475c2d) on Yunohost 3.3.3 (fresh install), failing on node not found : 
```
[7511.1] sh: 1: node: not found
[7511.1] + ynh_exit_properly
[7511.1] Webpacker requires Node.js >= 6.0.0 and you are using 4.8.2
[7511.1] + local exit_code=1
[7511.1] Please upgrade Node.js https://nodejs.org/en/download/
```
adding in script/install (SETUP SYSTEMD section) :
`ynh_replace_string "__ENV_PATH__" "$PATH" "../conf/mastodon-streaming.service"`

allow to go further but then fail on another error. For info this way is also used for Etherpad https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/master/conf/systemd.service

**=> Shouldn't you take it into account ?**

Remaining error is then on npm not found in /usr/bin ; creating the link from /opt/node_n/bin/npm allows to go a bit further but then complain on module 'throng' missing, in spite of installing with 'npm install throng' : 
```
> mastodon@ start /var/www/mastodon/live
> node ./streaming/index.js

module.js:550
    throw err;
    ^

Error: Cannot find module 'throng'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/mastodon/live/streaming/index.js:2:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mastodon@ start: `node ./streaming/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mastodon@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```
**==> Any advice is welcome**

**Comment by anmol26s** [comment]
You need to install nodejs
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages

**Comment by anubister** [comment]
It is installed : 
* as a Debian package dependancy (4.8.2~dfsg-1 so it looks too old for Mastodon according to the first error message)
* by `ynh_install_nodejs 8` from scripts/install ; i checked it is well installed in /opt/node_n/bin 
```
/opt/node_n/bin/node -v
v8.15.0
```

**Comment by anmol26s** [comment]
My npm version is

```
 npm -v
6.4.1
```
What  is your?

**Comment by anubister** [comment]
I have the same version in /opt/node_n/bin.

**Comment by anmol26s** [comment]
Do:

```
$ yarn cache clear
$ yarn install --pure-lockfile
$ yarn add throng
$ chown -R mastodon:mastodon /var/www/mastodon
$ service restart mastodon*
```

**Comment by anubister** [comment]
First command fails : 
```
$ yarn cache clear
/usr/share/yarn/lib/cli.js:45726
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by anmol26s** [comment]
I think you have to do in live folder
$ cd /var/www/mastodon/live

**Comment by anubister** [comment]
Thanks, it's progressing !
Now the 3 services status give a "active running" feedback.
But when I try to connect to the mastodon adress (so the root of my domain), I get a blank page (excepted the favicon) and the following in syslog : https://paste.yunohost.org/vuwuzugoju.go (something wrong with webpack).

**Comment by yalh76** [comment]
Can you try to install from  the last version.
Package has been updated
