### ISSUE TITLE
Restore failed on 1.4

### ISSUE THREAD

**Issue by nemsia** [YunoHost-Apps/mastodon_ynh#37]
Using /opt/mastodon/live/config/webpack/paths.yml file for setting up webpack paths
Compiling webpacker assets 🎉
Warning: Killed
Warning: rails aborted!
Warning: JSON::ParserError: 743: unexpected token at ''
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/webpacker-1.2/lib/tasks/webpacker/compile.rake:13:in `block (2 levels) in <top (required)>'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/webpacker-1.2/lib/tasks/webpacker/compile.rake:40:in `block in <top (required)>'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/commands.rb:18:in `<top (required)>'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
Warning: bin/rails:4:in `<main>'
Warning: Tasks: TOP => webpacker:compile
Warning: (See full trace by running task with --trace)
Error: Unable to restore the app 'mastodon'

**Comment by nemsia** [comment]
Fixed by https://github.com/YunoHost-Apps/mastodon_ynh/pull/38
