### ISSUE TITLE
[Help needed] Upgrade from 4.2.8~ynh1 to 4.2.10~ynh1 (maybe 4.2.8~ynh2 too) failed

### ISSUE THREAD

**Issue by Tony-John-Cil** [YunoHost-Apps/mastodon_ynh#458]
Hello, I'm trying to update the app from `4.2.8~ynh1` to `4.2.10~ynh1` but it fails and restores version 4.2.8 (I've tried with webadmin and CLI, I'm on YunoHost 11.2.20.2).

Error seems to trigger when Node packages are updated :
```
2024-07-14 13:02:32,954: DEBUG - + ynh_exec_warn_less ynh_exec_as mastodon RAILS_ENV=production PATH=/opt/rbenv/versions/mastodon/bin:/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/opt/rbenv/shims:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so bin/bundle exec rails assets:precompile
2024-07-14 13:02:32,954: DEBUG - + [[ 9 -eq 1 ]]
2024-07-14 13:02:32,954: DEBUG - + ynh_exec_as mastodon RAILS_ENV=production PATH=/opt/rbenv/versions/mastodon/bin:/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/opt/rbenv/shims:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so bin/bundle exec rails assets:precompile
2024-07-14 13:02:32,954: DEBUG - + local user=mastodon
2024-07-14 13:02:32,954: DEBUG - + shift 1
2024-07-14 13:02:32,954: DEBUG - ++ whoami
2024-07-14 13:02:32,954: DEBUG - + [[ mastodon = root ]]
2024-07-14 13:02:32,955: DEBUG - + sudo -u mastodon RAILS_ENV=production PATH=/opt/rbenv/versions/mastodon/bin:/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/opt/rbenv/shims:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so bin/bundle exec rails assets:precompile
2024-07-14 13:02:37,893: DEBUG - Compiling...
2024-07-14 13:05:56,706: DEBUG - Compilation failed:
2024-07-14 13:05:56,713: DEBUG - Browserslist: caniuse-lite is outdated. Please run:
2024-07-14 13:05:56,713: DEBUG -   npx update-browserslist-db@latest
2024-07-14 13:05:56,713: DEBUG -   Why you should do it regularly: https://github.com/browserslist/update-db#readme
2024-07-14 13:05:56,713: DEBUG - Browserslist: caniuse-lite is outdated. Please run:
2024-07-14 13:05:56,713: DEBUG -   npx update-browserslist-db@latest
2024-07-14 13:05:56,713: DEBUG -   Why you should do it regularly: https://github.com/browserslist/update-db#readme
2024-07-14 13:05:56,714: DEBUG - Browserslist: caniuse-lite is outdated. Please run:
2024-07-14 13:05:56,714: DEBUG -   npx update-browserslist-db@latest
2024-07-14 13:05:56,714: DEBUG -   Why you should do it regularly: https://github.com/browserslist/update-db#readme
2024-07-14 13:05:56,714: DEBUG - 
2024-07-14 13:05:57,227: DEBUG - + ynh_exit_properly
2024-07-14 13:05:57,228: DEBUG - + [[ upgrade =~ ^install$|^upgrade$|^restore$ ]]
2024-07-14 13:05:58,774: ERROR - Could not upgrade mastodon: An error occurred inside the app upgrade script
```

I'm able to execute `RAILS_ENV=production PATH=/opt/rbenv/versions/mastodon/bin:/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/opt/rbenv/shims:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so bin/bundle exec rails assets:precompile` as `mastodon` user and `sudo npx update-browserslist-db@latest` as admin user, both commands succeed, but update still doesn't work and print the same errors.

I should note that I've recently removed oldest versions of Node (12 and 14) on my server with `sudo rm -r /opt/node_n/n/versions/node/VERSION*`, it maybe caused the problem.

`/opt/node_n/ynh_app_version` contains (without duplicates) :
```
peertube:12
peertube:14
peertube:16
peertube:18
peertube:20
mastodon:12
mastodon:16
```

`ls -la /opt/node_n/n/versions/node/` prints (after removing oldest versions) :
```
drwxr-xr-x 20 root root 4096 Jul 14 11:44 .
drwxr-xr-x  3 root root 4096 Mar 13  2021 ..
lrwxrwxrwx  1 root root   35 Jul 14 06:25 16 -> /opt/node_n/n/versions/node/16.20.2
drwxr-xr-x  6 root root 4096 Dec 12  2021 16.13.1
drwxr-xr-x  6 root root 4096 Jan 26  2022 16.13.2
drwxrwxrwx  6 root root 4096 Feb 27  2022 16.14.0
drwxr-xr-x  6 root root 4096 Mar 31  2022 16.14.2
drwxrwxrwx  6 root root 4096 Jun 18  2022 16.15.1
drwxrwxrwx  6 root root 4096 Aug  4  2022 16.16.0
drwxr-xr-x  6 root root 4096 Sep  2  2022 16.17.0
drwxr-xr-x  6 root root 4096 Sep 24  2022 16.17.1
drwxr-xr-x  6 root root 4096 Nov 18  2022 16.18.1
drwxr-xr-x  6 root root 4096 Dec 17  2022 16.19.0
drwxr-xr-x  6 root root 4096 Feb 23  2023 16.19.1
drwxr-xr-x  6 root root 4096 Apr  8  2023 16.20.0
drwxr-xr-x  6 root root 4096 Jun 25  2023 16.20.1
drwxr-xr-x  6 root root 4096 Aug 21  2023 16.20.2
lrwxrwxrwx  1 root root   35 Jul 14 06:25 18 -> /opt/node_n/n/versions/node/18.19.0
drwxrwxrwx  6 root root 4096 Jan  6  2024 18.19.0
lrwxrwxrwx  1 root root   35 Jul 14 06:25 20 -> /opt/node_n/n/versions/node/20.15.0
drwxr-xr-x  6 root root 4096 Apr 18 16:39 20.12.2
drwxr-xr-x  6 root root 4096 Jun 22 14:22 20.15.0
drwxrwxrwx  6 root root 4096 Jul 14 11:44 20.15.1
```

Thanks in advance !

**Comment by Tony-John-Cil** [comment]
Update : I've just noticed that `4.2.8~ynh2` changed Node version from 16 to 20 some months ago, and that my `/opt/node_n/ynh_app_version` doesn't contain `mastodon:20`.

Moreover, as `root`, I've executed `sudo -u mastodon npx update-browserslist-db@latest`, then `sudo -u mastodon RAILS_ENV=production PATH=/opt/rbenv/versions/mastodon/bin:/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/opt/rbenv/shims:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so bin/bundle exec rails assets:precompile`, and I've got a new error :

```
Compilation failed:
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/var/www/mastodon/live/node_modules/babel-plugin-lodash/node_modules/@babel/types/lib/validators/generated/index.js:2740:35)
    at PluginPass.Program (/var/www/mastodon/live/node_modules/babel-plugin-lodash/lib/index.js:102:44)
```

If I try to update the app through the standard process after this, the `caniuse-lite` problem is back.

Is there any process I can follow to progressively update my instance (from `4.2.8~ynh1` to `4.2.8~ynh2` at first, change Node version for this app manually) ?

**Comment by Tony-John-Cil** [comment]
Update : for some reason, precompile now seems to work without any changes on my side, but I still can't upgrade the package, which now fails at the update config step.

```
2024-08-03 20:42:56,390: INFO - [#############++.....] > Updating a config file...
2024-08-03 20:42:56,392: DEBUG - ++ echo fr_FR
2024-08-03 20:42:56,393: DEBUG - ++ head -c 2
2024-08-03 20:42:56,399: DEBUG - + language=fr
2024-08-03 20:42:56,399: DEBUG - + ynh_add_config --template=.env.production.sample --destination=/var/www/mastodon/live/.env.production
2024-08-03 20:42:56,514: DEBUG - + jinja=0
2024-08-03 20:42:56,514: DEBUG - + '[' -f /var/cache/yunohost/app_tmp_work_dirs/app_no7gmh60/conf/.env.production.sample ']'
2024-08-03 20:42:56,515: DEBUG - + template_path=/var/cache/yunohost/app_tmp_work_dirs/app_no7gmh60/conf/.env.production.sample
2024-08-03 20:42:56,515: DEBUG - + ynh_backup_if_checksum_is_different --file=/var/www/mastodon/live/.env.production
2024-08-03 20:42:56,538: DEBUG - ++ ynh_app_setting_get --app=mastodon --key=checksum__var_www_mastodon_live_.env.production
2024-08-03 20:42:56,628: DEBUG - ++ [[ checksum__var_www_mastodon_live_.env.production =~ (unprotected|protected|skipped)_ ]]
2024-08-03 20:42:56,705: DEBUG - + local checksum_value=7255a2fc029a89f4e9c65a12386e45a5
2024-08-03 20:42:56,706: DEBUG - + backup_file_checksum=
2024-08-03 20:42:56,706: DEBUG - + '[' -n 7255a2fc029a89f4e9c65a12386e45a5 ']'
2024-08-03 20:42:56,706: DEBUG - + '[' -e /var/www/mastodon/live/.env.production ']'
2024-08-03 20:42:56,706: DEBUG - + md5sum --check --status
2024-08-03 20:42:56,710: DEBUG - + touch /var/www/mastodon/live/.env.production
2024-08-03 20:42:56,713: DEBUG - + chmod 640 /var/www/mastodon/live/.env.production
2024-08-03 20:42:56,715: DEBUG - + _ynh_apply_default_permissions /var/www/mastodon/live/.env.production
2024-08-03 20:42:56,715: DEBUG - + local target=/var/www/mastodon/live/.env.production
2024-08-03 20:42:56,716: DEBUG - ++ ynh_read_manifest --manifest_key=requirements.yunohost
2024-08-03 20:42:56,718: DEBUG - ++ tr -d '<>= '
2024-08-03 20:42:56,774: DEBUG - ++ '[' '!' -e '' ']'
2024-08-03 20:42:56,775: DEBUG - ++ '[' -e /var/cache/yunohost/app_tmp_work_dirs/app_no7gmh60/manifest.json ']'
2024-08-03 20:42:56,775: DEBUG - ++ '[' -e /var/cache/yunohost/app_tmp_work_dirs/app_no7gmh60/manifest.toml ']'
2024-08-03 20:42:56,776: DEBUG - ++ manifest=/var/cache/yunohost/app_tmp_work_dirs/app_no7gmh60/manifest.toml
2024-08-03 20:42:56,776: DEBUG - ++ echo /var/cache/yunohost/app_tmp_work_dirs/app_no7gmh60/manifest.toml
2024-08-03 20:42:56,777: DEBUG - ++ grep -q '\.json$'
2024-08-03 20:42:56,781: DEBUG - ++ python3 -c 'import json, toml, sys; print(json.dumps(toml.load(sys.stdin)))'
2024-08-03 20:42:56,782: DEBUG - ++ jq .requirements.yunohost --raw-output
2024-08-03 20:42:56,782: DEBUG - ++ cat /var/cache/yunohost/app_tmp_work_dirs/app_no7gmh60/manifest.toml
2024-08-03 20:42:56,847: DEBUG - + local ynh_requirement=null
2024-08-03 20:42:56,848: DEBUG - + dpkg --compare-versions 2.0 ge 2
2024-08-03 20:42:56,851: DEBUG - + chmod o-rwx /var/www/mastodon/live/.env.production
2024-08-03 20:42:56,854: DEBUG - + chmod g-w /var/www/mastodon/live/.env.production
2024-08-03 20:42:56,858: DEBUG - + chown -R root:root /var/www/mastodon/live/.env.production
2024-08-03 20:42:56,863: DEBUG - + ynh_system_user_exists mastodon
2024-08-03 20:42:56,895: DEBUG - + getent passwd mastodon
2024-08-03 20:42:56,898: DEBUG - + chown mastodon:mastodon /var/www/mastodon/live/.env.production
2024-08-03 20:42:56,900: DEBUG - + grep -qE '^(/etc/cron|/etc/php|/etc/nginx/conf.d|/etc/fail2ban|/etc/systemd/system)'
2024-08-03 20:42:56,904: DEBUG - + [[ 0 == 1 ]]
2024-08-03 20:42:56,904: DEBUG - + cp -f /var/cache/yunohost/app_tmp_work_dirs/app_no7gmh60/conf/.env.production.sample /var/www/mastodon/live/.env.production
2024-08-03 20:42:56,907: DEBUG - + ynh_replace_vars --file=/var/www/mastodon/live/.env.production
2024-08-03 20:42:56,936: DEBUG - + test -n /
2024-08-03 20:42:56,937: DEBUG - + local path_url_slash_less=
2024-08-03 20:42:56,937: DEBUG - + ynh_replace_string --match_string=__PATH__/ --replace_string=/ --target_file=/var/www/mastodon/live/.env.production
2024-08-03 20:42:57,117: DEBUG - + ynh_replace_string --match_string=__PATH__ --replace_string=/ --target_file=/var/www/mastodon/live/.env.production
2024-08-03 20:42:57,318: DEBUG - + test -n mastodon
2024-08-03 20:42:57,318: DEBUG - + ynh_replace_string --match_string=__NAME__ --replace_string=mastodon --target_file=/var/www/mastodon/live/.env.production
2024-08-03 20:42:57,516: DEBUG - + ynh_replace_string --match_string=__NAMETOCHANGE__ --replace_string=mastodon --target_file=/var/www/mastodon/live/.env.production
2024-08-03 20:42:57,741: DEBUG - + ynh_replace_string --match_string=__USER__ --replace_string=mastodon --target_file=/var/www/mastodon/live/.env.production
2024-08-03 20:42:57,906: DEBUG - + test -n ''
2024-08-03 20:42:57,907: DEBUG - + dpkg --compare-versions 2.0 lt 2
2024-08-03 20:42:57,911: DEBUG - + test -n PATH=/opt/rbenv/versions/mastodon/bin:/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/opt/rbenv/shims:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2024-08-03 20:42:57,912: DEBUG - + ynh_replace_string --match_string=__YNH_NODE_LOAD_PATH__ --replace_string=PATH=/opt/rbenv/versions/mastodon/bin:/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/opt/rbenv/shims:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --target_file=/var/www/mastodon/live/.env.production
2024-08-03 20:42:58,120: DEBUG - ++ grep -oP '__[A-Z0-9]+?[A-Z0-9_]*?[A-Z0-9]*?__' /var/www/mastodon/live/.env.production
2024-08-03 20:42:58,121: DEBUG - ++ sort --unique
2024-08-03 20:42:58,121: DEBUG - ++ sed 's@__\([^.]*\)__@\L\1@g'
2024-08-03 20:42:58,126: DEBUG - + uniques_vars=('app' 'db_name' 'db_pwd' 'db_user' 'domain' 'language' 'mail_pwd' 'otp_secret' 'redis_namespace' 'secret_key_base' 'vapid_private_key' 'vapid_public_key')
2024-08-03 20:42:58,197: WARNING - Variable $redis_namespace wasn't initialized when trying to replace __REDIS_NAMESPACE__ in /var/www/mastodon/live/.env.production
2024-08-03 20:42:58,198: DEBUG - + ynh_exit_properly
2024-08-03 20:42:58,198: DEBUG - + [[ upgrade =~ ^install$|^upgrade$|^restore$ ]]
```

The `$redis_namespace` seems to be missing, there's no reference of it in the whole journal, but I've noticed that the problem seems to come from the `4.2.8~ynh2` update like the previous one, the variable was removed from the upgrade script. How can I correct this ?

**Comment by Tony-John-Cil** [comment]
Trying to update again, now I'm back to the Node errors.

**Comment by przmkg** [comment]
I had the same problem as you and I ended up breaking my whole Mastodon install. The only thing that worked for me was to upgrade from the command line by skipping the backup. It is obviously **not recommended**.

`yunohost app upgrade -b`

**Comment by Tony-John-Cil** [comment]
Thanks for the suggestion !
I've tried one last time to upgrade through the standard process before testing the no-backup way ... and it worked.

I've seen that proposed version is now 4.2.12~ynh1, but it seems that there's no change that could explain why the upgrade works now. In the end, was the problem in the core app ?

Anyway, problem is solved now.
