### ISSUE TITLE
upgrade to `4.2.13~ynh1` is failing

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mastodon_ynh#477]
### Describe the bug

trying to upgrade `4.2.12~ynh1`    to  `4.2.13~ynh1`

### Context

- Hardware: *VPS*
- YunoHost version: 12.0.7
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: `4.2.13~ynh1`
- If upgrading, current package version: `4.2.12~ynh1`

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    yunohost app upgrade mastodon
    ```

### Logs

https://paste.yunohost.org/raw/ukodewibod

**Comment by isAAAc** [comment]
:up: 
am I the only one to encounter this issue?

**Comment by orhtej2** [comment]
There's no actual error in the log ☠️ 

If you type the following in the `bash` shell, what happens: `source /opt/rbenv/completions/rbenv.bash` ? What's the result of `echo $?` right after that one?

**Comment by isAAAc** [comment]
@orhtej2, 
thx for your answer , 
```
root@krashboyz:~# source /opt/rbenv/completions/rbenv.bash
root@krashboyz:~# echo $?
0
```

**Comment by orhtej2** [comment]
And if you issue (as root) `rbenv rehash` afterwards? What's the output of `echo $?` then?

**Comment by BishopGreer** [comment]
I too get a failure on 4.2.13. 

Log----

Error: Could not upgrade mastodon: An error occurred inside the app upgrade script
Info: The operation 'Upgrade the 'mastodon' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20241129-152244-app_upgrade-mastodon' to get help
Warning: Here's an extract of the logs before the crash. It might help debugging the error:
Info: DEBUG - /var/www/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `each'
Info: DEBUG - /var/www/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `block in require'
Info: DEBUG - /var/www/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `each'
Info: DEBUG - /var/www/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `require'
Info: DEBUG - /var/www/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler.rb:187:in `require'
Info: DEBUG - /var/www/mastodon/live/config/application.rb:24:in `<main>'
Info: DEBUG - <internal:/opt/rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
Info: DEBUG - <internal:/opt/rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
Info: DEBUG - /var/www/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
Info: DEBUG - /var/www/mastodon/live/Rakefile:6:in `<main>'
Info: DEBUG - /var/www/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8.4/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
Info: DEBUG - /var/www/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
Info: DEBUG - /var/www/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8.4/lib/rails/command.rb:51:in `invoke'
Info: DEBUG - /var/www/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8.4/lib/rails/commands.rb:18:in `<main>'
Info: DEBUG - <internal:/opt/rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
Info: DEBUG - <internal:/opt/rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
Info: DEBUG - /var/www/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
Info: DEBUG - bin/rails:4:in `<main>'
Info: DEBUG - (See full trace by running task with --trace)
Info: DEBUG - + ynh_exit_properly
Warning: Upgrade failed ... attempting to restore the safety backup (Yunohost first need to remove the app for this) ...
Info: Removing mastodon…
Info: [++++................] > Removing system configurations related to mastodon...
Info: [####++++............] > Removing mastodon-web service integration...
Info: [########++++........] > Removing mastodon-sidekiq service integration...
Info: [############++++....] > Removing mastodon-streaming service integration...
Info: Removing Ruby-3.2.3
Info: Removing rbenv

**Comment by isAAAc** [comment]
thx for your repport @BishopGreer  ;)  i feel myself less alone :)

@orhtej2 : 
```
root@krashboyz:~# cd /var/www/mastodon/live/
root@krashboyz:/var/www/mastodon/live# rbenv rehash
root@krashboyz:/var/www/mastodon/live# echo $?
0
root@krashboyz:/var/www/mastodon/live# source /opt/rbenv/completions/rbenv.bash
root@krashboyz:/var/www/mastodon/live# echo $?
0
```

**Comment by nschiwy** [comment]
Question for you both - how much RAM does your VPS have?

**Comment by BishopGreer** [comment]
My dedicated server has 24gb of ram.

**Comment by nschiwy** [comment]
Oh wow okay. That goes my theory, I guess. At least for your error. In my experience sometimes re-running the upgrade will just work the second time so that's worth trying if you haven't already. I also have had generally better experiences running from CLI rather than the web console. 

I was also going to suggest stopping all of the mastodon services before beginning the upgrade because that has helped me in the past but my issue is usually that the machine doesn't have enough RAM to run those services and the upgrade at the same time. Can't hurt to try though. It might be an issue with locked files as well.

**Comment by isAAAc** [comment]
i re-run the upgrade, but for me , same root-cause == same consequences :crossed_fingers: 

root@krashboyz:/# yunohost app upgrade mastodon
Info: Now upgrading mastodon…

wip

**Comment by isAAAc** [comment]
upgrade complete, 
but there are issues with MIME 
https://masto.krashboyz.org  , and open the console of your browser, 
i don't know how to fix it in yunohost context, nor if i am the onlyone to have this issue, 
tusky works well, 
android mastodon app is failing, 
on my tv it works
i'm a bit lost

ping @Tagadda 
hey , i saw your eyes, if you have any idea  :)

**Comment by isAAAc** [comment]
oh , i remember this  https://github.com/YunoHost-Apps/mastodon_ynh/issues/450

**Comment by isAAAc** [comment]
i tried what is suggested in #450 
partially works, 
133.0.3 (64-bit)  on debian: OK
128.5.2esr (64 bits) on debian: OK

but KO on an other laptop

looks KO on chromium too
```
root@krashboyz:/var/www/mastodon/live# sudo -u mastodon RAILS_ENV=production PATH=$PATH:/opt/rbenv/versions/mastodon/bin  bin/bundle exec rails assets:clobber
I, [2024-12-21T17:12:44.050039 #958841]  INFO -- : Removed /var/www/mastodon/live/public/assets
Webpacker requires Node.js ">=10.17.0" and you are using v6.17.1
Please upgrade Node.js https://nodejs.org/en/download/
Exiting!
```
```
root@krashboyz:/var/www/mastodon/live# cd /var/www/mastodon/live && sudo -u mastodon RAILS_ENV=production PATH=$PATH:/opt/rbenv/versions/mastodon/bin  bin/bundle exec rails assets:precompile
I, [2024-12-21T17:13:26.791389 #958924]  INFO -- : Writing /var/www/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css
I, [2024-12-21T17:13:26.792358 #958924]  INFO -- : Writing /var/www/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css.gz
I, [2024-12-21T17:13:26.832699 #958924]  INFO -- : Writing /var/www/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css
I, [2024-12-21T17:13:26.832960 #958924]  INFO -- : Writing /var/www/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css.gz
I, [2024-12-21T17:13:26.873695 #958924]  INFO -- : Writing /var/www/mastodon/live/public/assets/pghero/favicon-db10337a56c45eb43c22ff5019546b520fa22c7281d4d385f235cbca67ed26bb.png
I, [2024-12-21T17:13:26.952457 #958924]  INFO -- : Writing /var/www/mastodon/live/public/assets/pghero/application-fc5c893e805df52338bef3bda5a5431f74f1401da68e4f0381ac9ecb7a801e1a.js
I, [2024-12-21T17:13:26.952856 #958924]  INFO -- : Writing /var/www/mastodon/live/public/assets/pghero/application-fc5c893e805df52338bef3bda5a5431f74f1401da68e4f0381ac9ecb7a801e1a.js.gz
I, [2024-12-21T17:13:27.003943 #958924]  INFO -- : Writing /var/www/mastodon/live/public/assets/pghero/application-29fa393e673685cdbf2fb2b637098a15b988605f46bfa962f6e0cb94d15bc567.css
I, [2024-12-21T17:13:27.004344 #958924]  INFO -- : Writing /var/www/mastodon/live/public/assets/pghero/application-29fa393e673685cdbf2fb2b637098a15b988605f46bfa962f6e0cb94d15bc567.css.gz
Webpacker requires Node.js ">=10.17.0" and you are using v6.17.1
Please upgrade Node.js https://nodejs.org/en/download/
Exiting!
```

**Comment by isAAAc** [comment]
i don't understand how to manage the node version for webpack :/

**Comment by isAAAc** [comment]
i should managed something with this
```
root@krashboyz:/opt/node_n/n/versions/node# ls -al /opt/node_n
total 796
drwxr-xr-x 8 root root   4096 Nov 26 03:11 .
drwxr-xr-x 5 root root   4096 Nov 26 18:45 ..
drwxr-xr-x 2 root root   4096 Dec 20 18:22 bin
drwxr-xr-x 6 root root   4096 Nov 16  2021 git
drwxr-xr-x 3 root root   4096 Oct 27  2019 include
drwxr-xr-x 3 root root   4096 Oct 27  2019 lib
drwxr-xr-x 3 root root   4096 Oct 27  2019 n
-rw-r--r-- 1 root root 769109 Dec 21 06:27 node_update.log
-rwxr-xr-x 1 root root   1000 Jun 18  2024 node_update.sh
drwxr-xr-x 5 root root   4096 Oct 27  2019 share
-rw-r--r-- 1 root root    920 Dec 20 18:23 ynh_app_version
```
```root@krashboyz:/opt/node_n/n/versions/node# ls -al
total 244
drwxr-xr-x 61 root root 4096 Dec 21 06:27 .
drwxr-xr-x  4 root root 4096 Oct 27  2019 ..
lrwxrwxrwx  1 root root   35 Dec 21 06:25 10 -> /opt/node_n/n/versions/node/10.21.0
drwxr-xr-x  6 root root 4096 Nov 14  2019 10.17.0
drwxr-xr-x  6 root root 4096 Dec 18  2019 10.18.0
drwxr-xr-x  6 root root 4096 Jan 10  2020 10.18.1
drwxr-xr-x  6 root root 4096 Feb  6  2020 10.19.0
drwxr-xr-x  6 root root 4096 Apr  9  2020 10.20.0
drwxr-xr-x  6 root root 4096 Apr 13  2020 10.20.1
drwxr-xr-x  6 root root 4096 Jun 10  2020 10.21.0
lrwxrwxrwx  1 root root   36 Dec 21 06:25 12 -> /opt/node_n/n/versions/node/12.22.12
drwxr-xr-x  6 root root 4096 Aug  4  2020 12.18.3
drwxr-xr-x  6 root root 4096 Sep 16  2020 12.18.4
drwxr-xr-x  6 root root 4096 Oct 21  2020 12.19.0
drwxr-xr-x  6 root root 4096 Jan 20  2021 12.20.1
drwxr-xr-x  6 root root 4096 Mar 25  2021 12.21.0
drwxr-xr-x  6 root root 4096 Apr 11  2021 12.22.1
drwxr-xr-x  6 root root 4096 Feb 21  2022 12.22.10
drwxr-xr-x  6 root root 4096 May  5  2022 12.22.12
drwxr-xr-x  6 root root 4096 Jan 17  2022 12.22.9
lrwxrwxrwx  1 root root   35 Dec 21 06:25 14 -> /opt/node_n/n/versions/node/14.21.2
drwxr-xr-x  6 root root 4096 Apr 11  2021 14.16.1
drwxr-xr-x  6 root root 4096 May 17  2021 14.17.0
drwxr-xr-x  6 root root 4096 Jun 20  2021 14.17.1
drwxr-xr-x  6 root root 4096 Jul  9  2021 14.17.3
drwxr-xr-x  6 root root 4096 Aug  2  2021 14.17.4
drwxr-xr-x  6 root root 4096 Aug 20  2021 14.17.5
drwxr-xr-x  6 root root 4096 Sep  1  2021 14.17.6
drwxr-xr-x  6 root root 4096 Oct  5  2021 14.18.0
drwxr-xr-x  6 root root 4096 Oct 17  2021 14.18.1
drwxr-xr-x  6 root root 4096 Dec  1  2021 14.18.2
drwxrwxrwx  6 root root 4096 Mar  8  2022 14.19.0
drwxr-xr-x  6 root root 4096 Jan 17  2023 14.21.2
lrwxrwxrwx  1 root root   35 Dec 21 06:26 16 -> /opt/node_n/n/versions/node/16.20.2
lrwxrwxrwx  1 root root   35 Jul 11  2022 16.13 -> /opt/node_n/n/versions/node/16.13.2
drwxr-xr-x  6 root root 4096 Dec 13  2021 16.13.1
drwxr-xr-x  6 root root 4096 Feb  1  2022 16.13.2
drwxr-xr-x  6 root root 4096 Feb 21  2022 16.14.0
drwxr-xr-x  6 root root 4096 May  5  2022 16.15.0
drwxr-xr-x  6 root root 4096 Jul  1  2022 16.15.1
drwxr-xr-x  6 root root 4096 Jul 11  2022 16.16.0
drwxr-xr-x  6 root root 4096 Aug 17  2022 16.17.0
drwxr-xr-x  6 root root 4096 Nov  1  2022 16.18.0
drwxr-xr-x  6 root root 4096 Nov  5  2022 16.18.1
drwxrwxrwx  6 root root 4096 Dec 14  2022 16.19.0
drwxr-xr-x  6 root root 4096 Feb 20  2023 16.19.1
drwxr-xr-x  6 root root 4096 Mar 31  2023 16.20.0
drwxr-xr-x  6 root root 4096 Jun 26  2023 16.20.1
drwxr-xr-x  6 root root 4096 Aug 21  2023 16.20.2
lrwxrwxrwx  1 root root   35 Dec 21 06:26 18 -> /opt/node_n/n/versions/node/18.19.0
drwxr-xr-x  6 root root 4096 Jun  8  2023 18.16.0
drwxr-xr-x  6 root root 4096 Jul  6  2023 18.16.1
drwxr-xr-x  6 root root 4096 Aug 15  2023 18.17.1
drwxr-xr-x  6 root root 4096 Oct 18  2023 18.18.2
drwxr-xr-x  6 root root 4096 Jan 15  2024 18.19.0
lrwxrwxrwx  1 root root   35 Dec 21 06:27 20 -> /opt/node_n/n/versions/node/20.18.1
drwxr-xr-x  6 root root 4096 Feb 27  2024 20.11.1
drwxr-xr-x  6 root root 4096 Apr 16  2024 20.12.2
drwxr-xr-x  6 root root 4096 May 29  2024 20.14.0
drwxr-xr-x  6 root root 4096 Jun 24 19:30 20.15.0
drwxr-xr-x  6 root root 4096 Jul 21 17:16 20.15.1
drwxr-xr-x  6 root root 4096 Aug  6 13:47 20.16.0
drwxr-xr-x  6 root root 4096 Aug 21 20:56 20.17.0
drwxr-xr-x  6 root root 4096 Nov 15 10:59 20.18.0
drwxrwxrwx  6 root root 4096 Nov 26 18:55 20.18.1
drwxr-xr-x  6 root root 4096 Sep 25  2023 20.7.0
drwxr-xr-x  6 root root 4096 Oct  9  2023 20.8.0
lrwxrwxrwx  1 root root   34 Dec 21 06:27 6 -> /opt/node_n/n/versions/node/6.17.1
drwxr-xr-x  7 root root 4096 Oct 27  2019 6.17.1
```
```
root@krashboyz:/opt/node_n# grep -Ri mastodon ynh_app_version 
mastodon:16
mastodon:16
mastodon:16
mastodon:16
mastodon:16
mastodon:20
mastodon:20
```
why mastodon want to use a wrong version ... ><

**Comment by isAAAc** [comment]
```
root@krashboyz:/etc/systemd/system  cat mastodon-web.service

[Unit]
Description=mastodon-web
After=network.target

[Service]
Type=simple
User=mastodon
WorkingDirectory=/var/www/mastodon/live
Environment=""
Environment="RAILS_ENV=production"
Environment="PORT=3000"
Environment="PATH=/opt/rbenv/versions/mastodon/bin:/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/opt/rbenv/shims:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rbenv/shims:/opt/rbenv/bin:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rbenv/shims:/opt/rbenv/bin:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rbenv/shims:/opt/rbenv/bin:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rbenv/shims:/opt/rbenv/bin:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rbenv/shims:/opt/rbenv/bin:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rbenv/shims:/opt/rbenv/bin:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rbenv/shims:/opt/rbenv/bin:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rbenv/shims:/opt/rbenv/bin:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rbenv/shims:/opt/rbenv/bin:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rbenv/shims:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rbenv/shims:/opt/rbenv/bin:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ExecStart=/var/www/mastodon/live/bin/bundle exec puma -C config/puma.rb
ExecReload=/bin/kill -SIGUSR1 $MAINPID
TimeoutSec=15
Restart=always
StandardOutput=append:/var/log/mastodon/mastodon-web.log
StandardError=inherit

# Sandboxing options to harden security
# Depending on specificities of your service/app, you may need to tweak these 
# .. but this should be a good baseline
# Details for these options: https://www.freedesktop.org/software/systemd/man/systemd.exec.html
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
RestrictNamespaces=yes
RestrictRealtime=yes
DevicePolicy=closed
ProtectSystem=full
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
LockPersonality=yes
SystemCallFilter=~@clock @debug @module @mount @obsolete @reboot @setuid @swap

# Denying access to capabilities that should not be relevant for webapps
# Doc: https://man7.org/linux/man-pages/man7/capabilities.7.html
CapabilityBoundingSet=~CAP_RAWIO CAP_MKNOD
CapabilityBoundingSet=~CAP_AUDIT_CONTROL CAP_AUDIT_READ CAP_AUDIT_WRITE
CapabilityBoundingSet=~CAP_SYS_BOOT CAP_SYS_TIME CAP_SYS_MODULE CAP_SYS_PACCT
CapabilityBoundingSet=~CAP_LEASE CAP_LINUX_IMMUTABLE CAP_IPC_LOCK
CapabilityBoundingSet=~CAP_BLOCK_SUSPEND CAP_WAKE_ALARM
CapabilityBoundingSet=~CAP_SYS_TTY_CONFIG
CapabilityBoundingSet=~CAP_MAC_ADMIN CAP_MAC_OVERRIDE
CapabilityBoundingSet=~CAP_NET_ADMIN CAP_NET_BROADCAST CAP_NET_RAW
CapabilityBoundingSet=~CAP_SYS_ADMIN CAP_SYS_PTRACE CAP_SYSLOG 

[Install]
WantedBy=multi-user.target
```
it should use `versions/node/20`   via the `Environment="PATH`

**Comment by isAAAc** [comment]
i restore from backup :(

**Comment by isAAAc** [comment]
upgrade to `4.3.2~ynh1` worked, 
thx to @Tagadda for the help <3

i close this issue
