### ISSUE TITLE
Problème de backup de l'application

### ISSUE THREAD

**Issue by tibs245** [YunoHost-Apps/mastodon_ynh#57]
Hi,

I have a problem with the backup of Mastodon app. When I select mastodon ( Same only mastodon ) to backup it. This not work.

Action

```
POST /backup
{"locale":"en","apps":"mastodon","ignore_hooks":""}
```

Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 406, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 495, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/backup.py", line 2036, in backup_create
    backup_manager.collect_files()
  File "/usr/lib/moulinette/yunohost/backup.py", line 524, in collect_files
    self._compute_backup_size()
  File "/usr/lib/moulinette/yunohost/backup.py", line 756, in _compute_backup_size
    size = disk_usage(row['source'])
  File "/usr/lib/moulinette/yunohost/backup.py", line 2326, in disk_usage
    du_output = subprocess.check_output(['du', '-sb', path])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['du', '-sb', '/var/lib/postgresql/mastodon_db.sql']' returned non-zero exit status 1
```

Have you any idea ?

![screenshot-mastodon-backup-probleme](https://user-images.githubusercontent.com/4147037/31824196-a4826850-b5ae-11e7-9f8b-ee3481b33d7a.png)

**Comment by nemsia** [comment]
I look on this.

**Comment by nemsia** [comment]
Can you try make backup with this command ? :
`yunohost backup create --ignore-system --apps mastodon --verbose`
