### ISSUE TITLE
Installation fails on Debian Stretch 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/mastodon_ynh#87]
Hi
Fresh install fails on Debian Stretch.
Here are the logs

```
Please be aware that Encryptor v2.0.0 had a major security bug when using AES-*-GCM algorithms.

By default You will not be able to decrypt data that was previously encrypted using an AES-*-GCM algorithm.

Please see the README and https://github.com/attr-encrypted/encryptor/pull/22 for more information.


Post-install message from attr_encrypted:



WARNING: Several insecure default options and features were deprecated in attr_encrypted v2.0.0.

Additionally, there was a bug in Encryptor v2.0.0 that insecurely encrypted data when using an AES-*-GCM algorithm.

This bug was fixed but introduced breaking changes between v2.x and v3.x.

Please see the README for more information regarding upgrading to attr_encrypted v3.0.0.


Post-install message from paperclip:
##################################################
#  NOTE FOR UPGRADING FROM 4.3.0 OR EARLIER      #
##################################################

Paperclip is now compatible with aws-sdk >= 2.0.0.

If you are using S3 storage, aws-sdk >= 2.0.0 requires you to make a few small
changes:

* You must set the `s3_region`
* If you are explicitly setting permissions anywhere, such as in an initializer,
  note that the format of the permissions changed from using an underscore to
  using a hyphen. For example, `:public_read` needs to be changed to
  `public-read`.

For a walkthrough of upgrading from 4 to 5 and aws-sdk >= 2.0 you can watch
http://rubythursday.com/episodes/ruby-snack-27-upgrade-paperclip-and-aws-sdk-in-prep-for-rails-5
+ pushd /opt/mastodon/live
/opt/mastodon/live /var/cache/yunohost/from_file/mastodon_ynh-master/scripts
+ yarn install --pure-lockfile
yarn install v1.3.2-20171207.1756
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "/opt/mastodon/live/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Warning: error postcss-smart-import@0.7.5: The engine "yarn" is incompatible with this module. Expected version ">=0.17.0".
Warning: error An unexpected error occurred: "Found incompatible module".
Warning: !!
Warning:   mastodon install's script has encountered an error. Installation was cancelled.
Warning: !!
++ EXIT_PROPERLY
++ trap '' ERR
++ echo -e '\e[91m \e[1m'
 
++ echo -e '!!\n  mastodon install'\''s script has encountered an error. Installation was cancelled.\n!!'
++ type -t CLEAN_SETUP
++ CLEAN_SETUP
++ echo ''

++ sudo sed -i '\@"domain.tld/":@d' /etc/ssowat/conf.json
++ '[' 2.4 = 2.2 ']'
++ ynh_die
Warning: /usr/share/yunohost/helpers.d/print: line 4: $1: unbound variable
Executing script '/var/cache/yunohost/from_file/mastodon_ynh-master/scripts/remove'...
+ set -u
+ '[' '!' -e .fonctions ']'
+ source .fonctions
++ ynh_version=2.4
+ source /usr/share/yunohost/helpers
+++ run-parts --list /usr/share/yunohost/helpers.d
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/backend ']'

```

**Comment by nemsia** [comment]
How to remove Yarn 1.3.2? That is the problem. 
`Try apt-get remove --purge yarn`
And
`whereis yarn` 
To remove the old yarn
And install yarn 1.7.0.

**Comment by anmol26s** [comment]
Ok I have fixed the yarn issue now. But installation still fails.

```
Post-install message from paperclip:
##################################################
#  NOTE FOR UPGRADING FROM 4.3.0 OR EARLIER      #
##################################################

Paperclip is now compatible with aws-sdk >= 2.0.0.

If you are using S3 storage, aws-sdk >= 2.0.0 requires you to make a few small
changes:

* You must set the `s3_region`
* If you are explicitly setting permissions anywhere, such as in an initializer,
  note that the format of the permissions changed from using an underscore to
  using a hyphen. For example, `:public_read` needs to be changed to
  `public-read`.

For a walkthrough of upgrading from 4 to 5 and aws-sdk >= 2.0 you can watch
http://rubythursday.com/episodes/ruby-snack-27-upgrade-paperclip-and-aws-sdk-in-prep-for-rails-5
+ pushd /opt/mastodon/live
/opt/mastodon/live /var/cache/yunohost/from_file/mastodon_ynh-master/scripts
+ yarn install --pure-lockfile
yarn install v1.7.0
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 94.17s.
+ popd
/var/cache/yunohost/from_file/mastodon_ynh-master/scripts
+ pushd /opt/mastodon/live/
/opt/mastodon/live /var/cache/yunohost/from_file/mastodon_ynh-master/scripts
+ sudo cp -a .env.production.sample .env.production
+ sudo sed -i s@REDIS_HOST=redis@REDIS_HOST=127.0.0.1@g /opt/mastodon/live/.env.production
+ sudo sed -i s@DB_HOST=db@DB_HOST=/var/run/postgresql@g /opt/mastodon/live/.env.production
+ sudo sed -i s@DB_USER=postgres@DB_USER=mastodon@g /opt/mastodon/live/.env.production
+ sudo sed -i s@DB_NAME=postgres@DB_NAME=mastodon_production@g /opt/mastodon/live/.env.production
+ sudo sed -i s@LOCAL_DOMAIN=example.com@LOCAL_DOMAIN=mastadon.domain.tld@g /opt/mastodon/live/.env.production
++ head -c 2
++ echo en_EN
+ language=en
+ sudo sed -i 's@# DEFAULT_LOCALE=de@DEFAULT_LOCALE=en@g' /opt/mastodon/live/.env.production
++ head -n128 /dev/urandom
++ head -c128
++ tr -dc -d a-z0-9
++ tail -n +1
Warning: tr: write error: Broken pipe
+ paperclip_secret=orphkswx6eywwioq37b6poqp79y94ju0qz3kips4i03yhw3860iwubesij16rwc1h8qhv7z71nt46aq96o0vl70stfwjxgohiqurecemi1vjlpdy5ora7p74unt849hv
++ tr -dc -d a-z0-9
++ head -c128
++ tail -n +1
++ head -n128 /dev/urandom
Warning: tr: write error: Broken pipe
+ secret_key_base=eisobb8o9xpc95wdl2n7hxmbjclkjrijqetuz4j1zuubn94ozdjkzlllpx1fer74dl06i88hb0ng6p8h4mzhcqvh52sxx9h1b1umj89ufqj7heywtw1xzz78foz5bh2d
++ head -n128 /dev/urandom
++ tail -n +1
++ head -c128
++ tr -dc -d a-z0-9
+ otp_secret=27830bfpoyw8vqczybcr15mw09ww0mzawe0ewxff7iwb2q3f0uv7fzpecopmx2rjic3dfel2p4a5jn537cctm0dn0w0cowwnw2cm1ev3svua2tfjjt4ky7c9ta9i8kj0
+ sudo sed -i s@PAPERCLIP_SECRET=@PAPERCLIP_SECRET=orphkswx6eywwioq37b6poqp79y94ju0qz3kips4i03yhw3860iwubesij16rwc1h8qhv7z71nt46aq96o0vl70stfwjxgohiqurecemi1vjlpdy5ora7p74unt849hv@g /opt/mastodon/live/.env.production
+ sudo sed -i s@SECRET_KEY_BASE=@SECRET_KEY_BASE=eisobb8o9xpc95wdl2n7hxmbjclkjrijqetuz4j1zuubn94ozdjkzlllpx1fer74dl06i88hb0ng6p8h4mzhcqvh52sxx9h1b1umj89ufqj7heywtw1xzz78foz5bh2d@g /opt/mastodon/live/.env.production
+ sudo sed -i s@OTP_SECRET=@OTP_SECRET=27830bfpoyw8vqczybcr15mw09ww0mzawe0ewxff7iwb2q3f0uv7fzpecopmx2rjic3dfel2p4a5jn537cctm0dn0w0cowwnw2cm1ev3svua2tfjjt4ky7c9ta9i8kj0@g /opt/mastodon/live/.env.production
+ sudo sed -i s@SMTP_LOGIN=@#SMTP_LOGIN=@g /opt/mastodon/live/.env.production
+ sudo sed -i s@SMTP_PASSWORD=@#SMTP_PASSWORD=@g /opt/mastodon/live/.env.production
+ sudo sed -i s@SMTP_SERVER=smtp.mailgun.org@SMTP_SERVER=localhost@g /opt/mastodon/live/.env.production
+ sudo sed -i s@SMTP_PORT=587@SMTP_PORT=25@g /opt/mastodon/live/.env.production
+ sudo sed -i s,SMTP_FROM_ADDRESS=notifications@example.com,SMTP_FROM_ADDRESS=user@mastadon.domain.tld, /opt/mastodon/live/.env.production
+ sudo sed -i s@#SMTP_AUTH_METHOD=plain@SMTP_AUTH_METHOD=none@g /opt/mastodon/live/.env.production
+ sudo sed -i s@#SMTP_OPENSSL_VERIFY_MODE=peer@SMTP_OPENSSL_VERIFY_MODE=none@g /opt/mastodon/live/.env.production
+ sudo su - mastodon
~/live ~
Warning: PG::InvalidCatalogName: ERROR:  template database "template1" does not exist
Warning: : CREATE DATABASE "mastodon_production" ENCODING = 'unicode'
Warning: Couldn't create database for {"adapter"=>"postgresql", "pool"=>5, "timeout"=>5000, "encoding"=>"unicode", "database"=>"mastodon_production", "username"=>"mastodon", "password"=>nil, "host"=>"/var/run/postgresql", "port"=>5432, "prepared_statements"=>true}
Warning: rails aborted!
Warning: ActiveRecord::StatementInvalid: PG::InvalidCatalogName: ERROR:  template database "template1" does not exist
Warning: : CREATE DATABASE "mastodon_production" ENCODING = 'unicode'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `async_exec'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `block (2 levels) in execute'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:74:in `block in execute'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `execute'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/schema_statements.rb:46:in `create_database'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:119:in `create'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <top (required)>'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
Warning: bin/rails:4:in `<main>'
Warning: 
Warning: Caused by:
Warning: PG::InvalidCatalogName: ERROR:  template database "template1" does not exist
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `async_exec'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `block (2 levels) in execute'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:74:in `block in execute'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `execute'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/schema_statements.rb:46:in `create_database'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:119:in `create'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <top (required)>'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
Warning: /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
Warning: bin/rails:4:in `<main>'
Warning: Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create
Warning: (See full trace by running task with --trace)
++ EXIT_PROPERLY
++ trap '' ERR
++ echo -e '\e[91m \e[1m'
 
++ echo -e '!!\n  mastodon install'\''s script has encountered an error. Installation was cancelled.\n!!'
++ type -t CLEAN_SETUP
++ CLEAN_SETUP
++ echo ''

++ sudo sed -i '\@"mastadon.domain.tld/":@d' /etc/ssowat/conf.json
Warning: !!
Warning:   mastodon install's script has encountered an error. Installation was cancelled.
Warning: !!
Warning: /usr/share/yunohost/helpers.d/print: line 4: $1: unbound variable
++ '[' 2.4 = 2.2 ']'
++ ynh_die
Executing script '/var/cache/yunohost/from_file/mastodon_ynh-master/scripts/remove'...
+ set -u
+ '[' '!' -e .fonctions ']'
+ source .fonctions
++ ynh_version=2.4
+ source /usr/share/yunohost/helpers
+++ run-parts --list /usr/share/yunohost/helpers.d
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/backend ']'
++ . /usr/share/yunohost/helpers.d/backend
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/filesystem ']'
++ . /usr/share/yunohost/helpers.d/filesystem
+++ CAN_BIND=1
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/ip ']'
++ . /usr/share/yunohost/helpers.d/ip
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/mysql ']'
++ . /usr/share/yunohost/helpers.d/mysql
+++ MYSQL_ROOT_PWD_FILE=/etc/yunohost/mysql
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/network ']'
++ . /usr/share/yunohost/helpers.d/network
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/nodejs ']'
++ . /usr/share/yunohost/helpers.d/nodejs
+++ n_install_dir=/opt/node_n
+++ node_version_path=/opt/node_n/n/versions/node
+++ export N_PREFIX=/opt/node_n
+++ N_PREFIX=/opt/node_n
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/package ']'
++ . /usr/share/yunohost/helpers.d/package
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/print ']'
++ . /usr/share/yunohost/helpers.d/print
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/psql ']'
++ . /usr/share/yunohost/helpers.d/psql
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/setting ']'
++ . /usr/share/yunohost/helpers.d/setting
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/string ']'
++ . /usr/share/yunohost/helpers.d/string
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/system ']'
++ . /usr/share/yunohost/helpers.d/system
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/user ']'
++ . /usr/share/yunohost/helpers.d/user
++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
++ '[' -r /usr/share/yunohost/helpers.d/utils ']'
++ . /usr/share/yunohost/helpers.d/utils
+ app=mastodon
++ ynh_app_setting_get mastodon domain
++ sudo yunohost app setting mastodon domain --output-as plain --quiet
+ domain=mastadon.domain.tld
+ '[' -e /etc/systemd/system/mastodon-web.service ']'
+ '[' -e /etc/systemd/system/mastodon-sidekiq.service ']'
+ '[' -e /etc/systemd/system/mastodon-streaming.service ']'
+ sudo yunohost service status
+ grep -q mastodon-web
+ sudo yunohost service status
+ grep -q mastodon-sidekiq
+ grep -q mastodon-streaming
+ sudo yunohost service status
+ ynh_psql_drop_db mastodon_production
+ sudo su -c 'dropdb mastodon_production' postgres
Warning: dropdb: database removal failed: ERROR:  database "mastodon_production" does not exist
+ ynh_psql_drop_role mastodon
+ sudo su -c psql postgres
DROP ROLE
+ ynh_secure_remove /opt/mastodon
+ local path_to_remove=/opt/mastodon
+ local 'forbidden_path= 	/var/www 	/home/yunohost.app'
+ [[  	/var/www 	/home/yunohost.app =~ /opt/mastodon ]]
+ [[ /opt/mastodon =~ ^/[[:alnum:]]+$ ]]
+ [[ n = \/ ]]
+ '[' -e /opt/mastodon ']'
+ sudo rm -R /opt/mastodon
+ [[ -n mastadon.domain.tld ]]
+ sudo rm -f /etc/nginx/conf.d/mastadon.domain.tld.d/mastodon.conf
+ REMOVE_NGINX_CONF
Warning: /etc/cron.d/mastodon wasn't deleted because it doesn't exist.
+ '[' -e /etc/nginx/conf.d/mastadon.domain.tld.d/mastodon.conf ']'
+ ynh_secure_remove /etc/cron.d/mastodon
+ local path_to_remove=/etc/cron.d/mastodon
Warning: /etc/apt/sources.list.d/backports.list wasn't deleted because it doesn't exist.
+ local 'forbidden_path= 	/var/www 	/home/yunohost.app'
+ [[  	/var/www 	/home/yunohost.app =~ /etc/cron\.d/mastodon ]]
+ [[ /etc/cron.d/mastodon =~ ^/[[:alnum:]]+$ ]]
+ [[ n = \/ ]]
+ '[' -e /etc/cron.d/mastodon ']'
+ echo '/etc/cron.d/mastodon wasn'\''t deleted because it doesn'\''t exist.'
+ ynh_secure_remove /etc/apt/sources.list.d/backports.list
+ local path_to_remove=/etc/apt/sources.list.d/backports.list
+ local 'forbidden_path= 	/var/www 	/home/yunohost.app'
+ [[  	/var/www 	/home/yunohost.app =~ /etc/apt/sources\.list\.d/backports\.list ]]
+ [[ /etc/apt/sources.list.d/backports.list =~ ^/[[:alnum:]]+$ ]]
+ [[ t = \/ ]]
+ '[' -e /etc/apt/sources.list.d/backports.list ']'
+ echo '/etc/apt/sources.list.d/backports.list wasn'\''t deleted because it doesn'\''t exist.'
+ sudo userdel -f mastodon
+ sudo systemctl reload nginx
+ echo -e '\e[0m'

Success! The SSOwat configuration has been generated
Error: Installation failed
```

**Comment by nemsia** [comment]
Postgresql is in bad state, have you :
`apt-get remove --purge postgresql`
And

`rm -rfv /var/lib/postgresql`

**Comment by nemsia** [comment]
You resolved your problem ?

**Comment by anmol26s** [comment]
No, its not working for me on Debian Stretch. The creation of database fails https://github.com/YunoHost-Apps/mastodon_ynh/blob/master/scripts/install#L88
You should use the latest commands to create the database.
Eg. Peertube
https://github.com/YunoHost-Apps/peertube_ynh/blob/testing/scripts/psql.sh
https://github.com/YunoHost-Apps/peertube_ynh/blob/testing/scripts/install#L112

**Comment by nemsia** [comment]
That's planned on the [testing branch](https://github.com/nemsia/mastodon_ynh/tree/testing-2.4) made by @Jibec, he have made some change on this app and on peertube but the upgrade not working well.
If you wan't test this you are welcome. The install script work well.

**Comment by anmol26s** [comment]
You should push testing to master as soon as possible. Otherwise the master installation delete the template1 from the database resulting to an error message: 
`ERROR:  template database "template1" does not exist
`

**Comment by nemsia** [comment]
Fixed by https://github.com/YunoHost-Apps/mastodon_ynh/pull/96
