### ISSUE TITLE
install failed on jessie 

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mastodon_ynh#89]
hi, 
i tried to install mastodon on a VPS, but install failed : 
```
2018-06-12 12:44:28,337 INFO     yunohost.hook <lambda> - [6201.1] ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
2018-06-12 12:44:28,375 INFO     yunohost.hook <lambda> - [6201.1] + sudo ln -s /opt/mastodon/.rbenv/versions/2.4.1/bin/ruby /usr/bin/ruby
2018-06-12 12:44:28,453 INFO     yunohost.hook <lambda> - [6201.1] + sudo su - mastodon
2018-06-12 12:44:28,909 INFO     yunohost.hook <lambda> - [6201.1] ~/live ~
2018-06-12 12:44:35,157 INFO     yunohost.hook <lambda> - [6201.1] Successfully installed bundler-1.16.2
2018-06-12 12:44:35,158 INFO     yunohost.hook <lambda> - [6201.1] Parsing documentation for bundler-1.16.2
2018-06-12 12:44:35,158 INFO     yunohost.hook <lambda> - [6201.1] Installing ri documentation for bundler-1.16.2
2018-06-12 12:44:35,158 INFO     yunohost.hook <lambda> - [6201.1] Done installing documentation for bundler after 5 seconds
2018-06-12 12:44:35,158 INFO     yunohost.hook <lambda> - [6201.1] 1 gem installed
2018-06-12 12:44:35,338 WARNING  yunohost.hook <lambda> - [6201.1] rbenv: version `2.5.1' is not installed (set by /opt/mastodon/live/.ruby-version)
2018-06-12 12:44:35,511 WARNING  yunohost.hook <lambda> - [6201.1] rbenv: version `2.5.1' is not installed (set by /opt/mastodon/live/.ruby-version)
2018-06-12 12:44:35,529 INFO     yunohost.hook <lambda> - [6201.1] ++ EXIT_PROPERLY
2018-06-12 12:44:35,529 INFO     yunohost.hook <lambda> - [6201.1] ++ trap '' ERR
2018-06-12 12:44:35,529 INFO     yunohost.hook <lambda> - [6201.1] ++ echo -e '\e[91m \e[1m'
2018-06-12 12:44:35,530 INFO     yunohost.hook <lambda> - [6201.1]
2018-06-12 12:44:35,530 INFO     yunohost.hook <lambda> - [6201.1] ++ echo -e '!!\n  mastodon install'\''s script has encountered an error. Installation was cancelled.\n!!'
```
yunohost -v : 

yunohost:
```
  repo: stable
  version: 2.7.12
yunohost-admin:
  repo: stable
  version: 2.7.12
moulinette:
  repo: stable
  version: 2.7.12
ssowat:
  repo: stable
  version: 2.7.12
```

**Comment by isAAAc** [comment]
ln -s /opt/mastodon/.rbenv/versions/2.4.1/bin/ruby /usr/bin/ruby : 
`ln: impossible de créer le lien symbolique « /usr/bin/ruby »: Le fichier existe`
file already exists :/ 

install failed again, looks like a db create failure if i well understand (?) : 
```
For a walkthrough of upgrading from 4 to 5 and aws-sdk >= 2.0 you can watch
http://rubythursday.com/episodes/ruby-snack-27-upgrade-paperclip-and-aws-sdk-in-prep-for-rails-5
+ pushd /opt/mastodon/live
/opt/mastodon/live /var/cache/yunohost/from_file/mastodon_ynh-master/scripts
+ yarn install --pure-lockfile
yarn install v1.7.0
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 70.44s.
+ popd
/var/cache/yunohost/from_file/mastodon_ynh-master/scripts
+ pushd /opt/mastodon/live/
/opt/mastodon/live /var/cache/yunohost/from_file/mastodon_ynh-master/scripts
+ sudo cp -a .env.production.sample .env.production
+ sudo sed -i s@REDIS_HOST=redis@REDIS_HOST=127.0.0.1@g /opt/mastodon/live/.env.production
+ sudo sed -i s@DB_HOST=db@DB_HOST=/var/run/postgresql@g /opt/mastodon/live/.env.production
+ sudo sed -i s@DB_USER=postgres@DB_USER=mastodon@g /opt/mastodon/live/.env.production
+ sudo sed -i s@DB_NAME=postgres@DB_NAME=mastodon_production@g /opt/mastodon/live/.env.production
+ sudo sed -i s@LOCAL_DOMAIN=example.com@LOCAL_DOMAIN=masto.krashboyz.org@g /opt/mastodon/live/.env.production
++ echo fr_FR
++ head -c 2
+ language=fr
+ sudo sed -i 's@# DEFAULT_LOCALE=de@DEFAULT_LOCALE=fr@g' /opt/mastodon/live/.env.production
++ head -n128 /dev/urandom
++ tail -n +1
++ tr -dc -d a-z0-9
++ head -c128
+ paperclip_secret=0ll8c8qqvi120hw8mxdw9b7dbdhonptdjpr3nwfh1ra12ys9bqc77gx78dwc5ovm2bi3fsu3baqqknwbqcbfvlvw0pp4c8k1tr9xw49rbd6amtmw6sch0ks0eslgofhf
++ head -n128 /dev/urandom
++ tail -n +1
++ head -c128
++ tr -dc -d a-z0-9
+ secret_key_base=mxxbsilgow27mawm5qrkt8y6soq54h2yafj55n7z9nsf5lkzx1iwbz1fmwtkrk1hojgte4q4xfkg72rvewtn3z6qkvyg0d7dp8mjo5e2u4s8fn6a3pq3vm0nhuh1r2bc
++ head -n128 /dev/urandom
++ head -c128
++ tail -n +1
++ tr -dc -d a-z0-9
+ otp_secret=f4mym0ymzu2gjr62bk99ujgymr9vcvjseauaiyd5m3987qy3c3uk0gy983ys11rz08zmw97lpfkjkw51r6zum1pubv71t4e4qi10fescph8e0f44m2pv8o1f6jksi3yp
+ sudo sed -i s@PAPERCLIP_SECRET=@PAPERCLIP_SECRET=0ll8c8qqvi120hw8mxdw9b7dbdhonptdjpr3nwfh1ra12ys9bqc77gx78dwc5ovm2bi3fsu3baqqknwbqcbfvlvw0pp4c8k1tr9xw49rbd6amtmw6sch0ks0eslgofhf@g /opt/mastodon/live/.env.production
+ sudo sed -i s@SECRET_KEY_BASE=@SECRET_KEY_BASE=mxxbsilgow27mawm5qrkt8y6soq54h2yafj55n7z9nsf5lkzx1iwbz1fmwtkrk1hojgte4q4xfkg72rvewtn3z6qkvyg0d7dp8mjo5e2u4s8fn6a3pq3vm0nhuh1r2bc@g /opt/mastodon/live/.env.production
+ sudo sed -i s@OTP_SECRET=@OTP_SECRET=f4mym0ymzu2gjr62bk99ujgymr9vcvjseauaiyd5m3987qy3c3uk0gy983ys11rz08zmw97lpfkjkw51r6zum1pubv71t4e4qi10fescph8e0f44m2pv8o1f6jksi3yp@g /opt/mastodon/live/.env.production
+ sudo sed -i s@SMTP_LOGIN=@#SMTP_LOGIN=@g /opt/mastodon/live/.env.production
+ sudo sed -i s@SMTP_PASSWORD=@#SMTP_PASSWORD=@g /opt/mastodon/live/.env.production
+ sudo sed -i s@SMTP_SERVER=smtp.mailgun.org@SMTP_SERVER=localhost@g /opt/mastodon/live/.env.production
+ sudo sed -i s@SMTP_PORT=587@SMTP_PORT=25@g /opt/mastodon/live/.env.production
+ sudo sed -i s,SMTP_FROM_ADDRESS=notifications@example.com,SMTP_FROM_ADDRESS=isaaac@masto.krashboyz.org, /opt/mastodon/live/.env.production
+ sudo sed -i s@#SMTP_AUTH_METHOD=plain@SMTP_AUTH_METHOD=none@g /opt/mastodon/live/.env.production
+ sudo sed -i s@#SMTP_OPENSSL_VERIFY_MODE=peer@SMTP_OPENSSL_VERIFY_MODE=none@g /opt/mastodon/live/.env.production
+ sudo su - mastodon
~/live ~
Attention : fe_sendauth: no password supplied
Attention : Couldn't create database for {"adapter"=>"postgresql", "pool"=>5, "timeout"=>5000, "encoding"=>"unicode", "database"=>"mastodon_production", "username"=>"mastodon", "password"=>nil, "host"=>"/var/run/postgresql", "port"=>5432, "prepared_statements"=>true}
Attention : rails aborted!
Attention : PG::ConnectionBad: fe_sendauth: no password supplied
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/pg-1.0.0/lib/pg.rb:56:in `initialize'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/pg-1.0.0/lib/pg.rb:56:in `new'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/pg-1.0.0/lib/pg.rb:56:in `connect'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:684:in `connect'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `initialize'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `new'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `postgresql_connection'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_handling.rb:90:in `connection'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:119:in `create'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <top (required)>'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
Attention : /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
Attention : bin/rails:4:in `<main>'
Attention : Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create
Attention : (See full trace by running task with --trace)
++ EXIT_PROPERLY
++ trap '' ERR
++ echo -e '\e[91m \e[1m'

++ echo -e '!!\n  mastodon install'\''s script has encountered an error. Installation was cancelled.\n!!'
++ type -t CLEAN_SETUP
++ CLEAN_SETUP
++ echo ''

++ sudo sed -i '\@"masto.krashboyz.org/":@d' /etc/ssowat/conf.json
Attention : !!
Attention :   mastodon install's script has encountered an error. Installation was cancelled.
Attention : !!
++ '[' 2.4 = 2.2 ']'
++ ynh_die
Attention : /usr/share/yunohost/helpers.d/print: ligne 4: $1 : variable sans liaison
Exécution du script « /var/cache/yunohost/from_file/mastodon_ynh-master/scripts/remove »...
```

**Comment by nemsia** [comment]
If you have peertube installed on the same host you have this problem:
try with this new branch:
`sudo yunohost app install https://github.com/YunoHost-Apps/mastodon_ynh/tree/testing-2.4 --verbose`

**Comment by isAAAc** [comment]
yes peertube is installed on the same host on an other ndd, 

but install fail again with the command line you gave : 
```

Migrating to FixAccountsUniqueIndex (20180528141303)
== 20180528141303 FixAccountsUniqueIndex: migrating ===========================
--
-- WARNING: This migration may take a *long* time for large instances
-- It will *not* lock tables for any significant time, but it may run
-- for a very long time. We will pause for 10 seconds to allow you to
-- interrupt this migration if you are not ready.
--
-- This migration will irreversibly delete user accounts with duplicate
-- usernames. You may use the `rake mastodon:maintenance:find_duplicate_usernames`
-- task to manually deal with such accounts before running this migration.
   -> Continuing in 10 seconds...
   -> Continuing in 9 seconds...
   -> Continuing in 8 seconds...
   -> Continuing in 7 seconds...
   -> Continuing in 6 seconds...
   -> Continuing in 5 seconds...
   -> Continuing in 4 seconds...
   -> Continuing in 3 seconds...
   -> Continuing in 2 seconds...
   -> Continuing in 1 second...
-- index_name_exists?(:accounts, "index_accounts_on_username_and_domain_lower")
   -> 0.0010s
-- remove_index(:accounts, {:name=>"index_accounts_on_username_and_domain_lower"})
   -> 0.0019s
-- execute("CREATE UNIQUE INDEX CONCURRENTLY index_accounts_on_username_and_domain_lower ON accounts (lower(username), lower(domain))")
   -> 0.0047s
-- index_name_exists?(:accounts, "index_accounts_on_username_and_domain")
   -> 0.0018s
-- remove_index(:accounts, {:name=>"index_accounts_on_username_and_domain"})
   -> 0.0015s
== 20180528141303 FixAccountsUniqueIndex: migrated (10.0704s) =================

Migrating to RejectFollowingBlockedUsers (20180608213548)
== 20180608213548 RejectFollowingBlockedUsers: migrating ======================
-- Destroying 0 blocked follow relationships...
== 20180608213548 RejectFollowingBlockedUsers: migrated (0.0097s) =============

Migrating to MigrateWebPushSubscriptions2 (20180609104432)
== 20180609104432 MigrateWebPushSubscriptions2: migrating =====================
== 20180609104432 MigrateWebPushSubscriptions2: migrated (0.0118s) ============

Attention : I, [2018-06-13T16:45:44.697772 #15296]  INFO -- : Writing /var/www/mastodon/live/public/assets/doorkeeper/admin/application-50d68ad91b15067c63771e4811d971d7a56406c472a878021d1fb95d066efd8d.css
Attention : I, [2018-06-13T16:45:44.698090 #15296]  INFO -- : Writing /var/www/mastodon/live/public/assets/doorkeeper/admin/application-50d68ad91b15067c63771e4811d971d7a56406c472a878021d1fb95d066efd8d.css.gz
Attention : I, [2018-06-13T16:45:44.709706 #15296]  INFO -- : Writing /var/www/mastodon/live/public/assets/doorkeeper/application-29873392fba1f6a4fd5359214f854d900e24920096164f6e5343dbc0de69df0d.css
Attention : I, [2018-06-13T16:45:44.709807 #15296]  INFO -- : Writing /var/www/mastodon/live/public/assets/doorkeeper/application-29873392fba1f6a4fd5359214f854d900e24920096164f6e5343dbc0de69df0d.css.gz
Attention : I, [2018-06-13T16:45:44.721228 #15296]  INFO -- : Writing /var/www/mastodon/live/public/assets/pghero/favicon-db10337a56c45eb43c22ff5019546b520fa22c7281d4d385f235cbca67ed26bb.png
Attention : I, [2018-06-13T16:45:45.043108 #15296]  INFO -- : Writing /var/www/mastodon/live/public/assets/pghero/application-b6568ba483c03c4fdcd8edd641f3b341ac0314ba01ab186645b8fc231cdff02e.js
Attention : I, [2018-06-13T16:45:45.043365 #15296]  INFO -- : Writing /var/www/mastodon/live/public/assets/pghero/application-b6568ba483c03c4fdcd8edd641f3b341ac0314ba01ab186645b8fc231cdff02e.js.gz
Attention : I, [2018-06-13T16:45:45.060272 #15296]  INFO -- : Writing /var/www/mastodon/live/public/assets/pghero/application-d7ee8e7dc0785de97337625e0f1030e1a892327ef4e72a48043ce09fd964874d.css
Attention : I, [2018-06-13T16:45:45.062836 #15296]  INFO -- : Writing /var/www/mastodon/live/public/assets/pghero/application-d7ee8e7dc0785de97337625e0f1030e1a892327ef4e72a48043ce09fd964874d.css.gz
Webpacker is installed 🎉 🍰
Using /var/www/mastodon/live/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:


+ ynh_exit_properly
+ local exit_code=1
+ '[' 1 -eq 0 ']'
+ trap '' EXIT
+ set +eu
+ echo -e '!!\n  mastodon'\''s script has encountered an error. Its execution was cancelled.\n!!'
+ type -t ynh_clean_setup
```

**Comment by nemsia** [comment]
How many Ram have you on your VPS ?

**Comment by isAAAc** [comment]
> How many Ram have you on your VPS ?
-> 2Gig
but nevermind, i won't install mastodon finally , 
you can close the issue

**Comment by nemsia** [comment]
Sorry for this, if you change your mind a version that is fully compatible with [peertube_ynh](https://github.com/YunoHost-Apps/peertube_ynh) arrives in the coming days.
