### ISSUE TITLE
Problem on stretch

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/mastodon_ynh#97]
Hello, 
I tried to install mastodon on my own instance (for the first time ;)) but I go a problem : 
```473571 DEBUG + sudo sed -i s@#SMTP_OPENSSL_VERIFY_MODE=peer@SMTP_OPENSSL_VERIFY_MODE=none@g /opt/mastodon/live/.env.production
473581 DEBUG + sudo su - mastodon
473631 DEBUG ~/live ~
476367 WARNING fe_sendauth: no password supplied
476367 WARNING Couldn't create database for {"adapter"=>"postgresql", "pool"=>5, "timeout"=>5000, "encoding"=>"unicode", "database"=>"mastodon_production", "username"=>"mastodon", "password"=>nil, "host"=>"/var/run/postgresql", "port"=>5432, "prepared_statements"=>true}
476367 WARNING rails aborted!
476367 WARNING PG::ConnectionBad: fe_sendauth: no password supplied
476367 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/pg-1.0.0/lib/pg.rb:56:in `initialize'
476367 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/pg-1.0.0/lib/pg.rb:56:in `new'
476367 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/pg-1.0.0/lib/pg.rb:56:in `connect'
476367 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:684:in `connect'
476368 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `initialize'
476368 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `new'
476368 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `postgresql_connection'
476368 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
476368 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
476368 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
476368 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
476368 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
476368 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
476368 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
476368 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
476368 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_handling.rb:90:in `connection'
476369 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
476369 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
476369 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:119:in `create'
476369 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
476369 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
476369 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each'
476369 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
476369 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
476369 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <top (required)>'
476369 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
476370 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
476370 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
476370 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
476370 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
476370 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
476371 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
476371 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
476371 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
476371 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
476371 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
476371 WARNING /opt/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
476371 WARNING bin/rails:4:in `<main>'
476371 WARNING Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create
476371 WARNING (See full trace by running task with --trace)
```

I don't understand the error, but perhaps you know it.
Thanks in advance for your answer,
frju365

**Comment by nemsia** [comment]
Try with this branch:
`yunohost app install https://github.com/YunoHost-Apps/mastodon_ynh/tree/testing-2.4` it fully work for new instance. Just need many test to don't break actual mastodon instance.

**Comment by frju365** [comment]
It's works fine ! Thank you !
